apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-86-tenant/load-app-118110a8-4fec-464a-b0ae-590108c437cf/devfile-sample-go-basic@sha256:e084d47066a96e710bcfa5284f30ae38fec34b4764bda95f617cb115b317c821
        name: my-go
        resources: {}
status: {}
